traduzioni = {
    "🇮🇹 Italiano": {
        "titolo": "Il Gelato Artigianale",
        "lingua_nome": "Italiano",
        "ingredienti_label": "Inserisci i grammi degli ingredienti:",
        "calcola": "Calcola Bilanciamento",
        "risultati": "Risultati Bilanciamento:",
        "salva_ricetta": "Salva Ricetta",
        "carica_ricetta": "Carica Ricetta",
        "condividi": "Condividi",
        "esci": "Esci",
        "zuccheri_totali": "Zuccheri totali",
        "grassi_totali": "Grassi totali",
        "slm": "Solidi non Grassi (SLM)",
        "solidi_totali": "Solidi totali",
        "pod": "POD - Potere Dolcificante",
        "pac": "PAC - Potere Anticongelante",
        "altri_solidi": "Altri Solidi",
        "slng": "Solidi del Latte Non Grassi (SLNG)",
        "neutro_5": "Neutro 5 (Tara, Guar)",
        "avviso_latte_scremato": "Il latte scremato in polvere supera il 12% del peso totale",
        "condividi_testo_iniziale": "Ecco la mia ricetta per il gelato:\n\n",
        "condividi_risultati": "\nRisultati del bilanciamento:\n",
        "placeholder": "Inserisci i grammi",
        "guida": "Guida",
        "guida_titolo": "Guida all'uso",
        "guida_testo": "Ti è mai capitato di trovare grumi in un gelato o di assaggiarne uno che si scioglie troppo in fretta? Questi difetti nascono spesso da un errato bilanciamento degli ingredienti. Se la miscela non è equilibrata, il gelato può risultare troppo liquido, duro o sabbioso, a causa della formazione di cristalli di ghiaccio o lattosio. Anche il gusto ne risente, diventando eccessivamente dolce.\n\nUn buon bilanciamento, invece, garantisce un gelato cremoso, dalla giusta consistenza, senza grumi e con un sapore armonioso.\n\nSembra facile, ma bilanciare un gelato è un’arte!\n\nInserisci i grammi degli ingredienti e premi 'Calcola' per ottenere la ricetta perfetta.",
        "errore_input": "Errore: Inserisci solo numeri nei campi.",
        "errore_peso_zero": "Errore: Il peso totale degli ingredienti non può essere zero.",
        "ingredienti": {
            "Latte": "Latte",
            "Panna": "Panna",
            "Latte Scremato Polvere": "Latte Scremato Polvere",
            "Saccarosio": "Saccarosio",
            "Destrosio": "Destrosio",
            "Glucosio": "Glucosio",
            "Frutta Secca": "Frutta Secca",
            "Frutta Fresca": "Frutta Fresca",
            "Inulina": "Inulina",
        },
    },
    "🇬🇧 English": {
        "titolo": "The Artisan Gelato",
        "lingua_nome": "English",
        "ingredienti_label": "Enter the grams of ingredients:",
        "calcola": "Calculate Balance",
        "risultati": "Balance Results:",
        "salva_ricetta": "Save Recipe",
        "carica_ricetta": "Load Recipe",
        "condividi": "Share",
        "esci": "Exit",
        "zuccheri_totali": "Total Sugars",
        "grassi_totali": "Total Fats",
        "slm": "Non-Fat Solids (SLM)",
        "solidi_totali": "Total Solids",
        "pod": "POD - Sweetening Power",
        "pac": "PAC - Antifreeze Power",
        "altri_solidi": "Other Solids",
        "slng": "Non-Fat Milk Solids (SLNG)",
        "neutro_5": "Neutro 5 (Tara, Guar)",
        "avviso_latte_scremato": "Skimmed milk powder exceeds 12% of the total weight",
        "condividi_testo_iniziale": "Here is my gelato recipe:\n\n",
        "condividi_risultati": "\nBalance Results:\n",
        "placeholder": "Enter grams",
        "guida": "Guide",
        "guida_titolo": "User Guide",
        "guida_testo": "Have you ever found lumps in gelato or tasted one that melts too quickly? These defects often arise from an incorrect balance of ingredients. If the mixture is not balanced, the gelato can turn out too liquid, hard, or sandy due to the formation of ice or lactose crystals. The taste can also be affected, becoming overly sweet.\n\nA good balance, on the other hand, ensures a creamy gelato with the right consistency, no lumps, and a harmonious flavor.\n\nIt may seem easy, but balancing gelato is an art!\n\nEnter the grams of the ingredients and press 'Calculate' to get the perfect recipe.",
        "errore_input": "Error: Please enter only numbers in the fields.",
        "errore_peso_zero": "Error: The total weight of ingredients cannot be zero.",
        "ingredienti": {
            "Latte": "Milk",
            "Panna": "Cream",
            "Latte Scremato Polvere": "Skimmed Milk Powder",
            "Saccarosio": "Sucrose",
            "Destrosio": "Dextrose",
            "Glucosio": "Glucose",
            "Frutta Secca": "Dried Fruit",
            "Frutta Fresca": "Fresh Fruit",
            "Inulina": "Inulin",
        },
    },
    "🇫🇷 Français": {
        "titolo": "Le Gelato Artisanal",
        "lingua_nome": "Français",
        "ingredienti_label": "Entrez les grammes des ingrédients:",
        "calcola": "Calculer l'Équilibre",
        "risultati": "Résultats de l'Équilibre:",
        "salva_ricetta": "Sauvegarder la Recette",
        "carica_ricetta": "Charger la Recette",
        "condividi": "Partager",
        "esci": "Quitter",
        "zuccheri_totali": "Sucres Totaux",
        "grassi_totali": "Graisses Totales",
        "slm": "Solides Non Gras (SLM)",
        "solidi_totali": "Solides Totaux",
        "pod": "POD - Pouvoir Sucrant",
        "pac": "PAC - Pouvoir Antigel",
        "altri_solidi": "Autres Solides",
        "slng": "Solides Lactés Non Gras (SLNG)",
        "neutro_5": "Neutro 5 (Tara, Guar)",
        "avviso_latte_scremato": "La poudre de lait écrémé dépasse 12% du poids total",
        "condividi_testo_iniziale": "Voici ma recette de glace :\n\n",
        "condividi_risultati": "\nRésultats de l'équilibre :\n",
        "placeholder": "Entrez les grammes",
        "guida": "Guide",
        "guida_titolo": "Guide d'utilisation",
        "guida_testo": "Vous est-il déjà arrivé de trouver des grumeaux dans une glace ou d'en goûter une qui fond trop vite ? Ces défauts proviennent souvent d'un mauvais équilibre des ingrédients. Si le mélange n'est pas équilibré, la glace peut être trop liquide, dure ou granuleuse à cause de la formation de cristaux de glace ou de lactose. Le goût peut également en pâtir, devenant trop sucré.\n\nUn bon équilibre, en revanche, garantit une glace crémeuse, avec la bonne consistance, sans grumeaux et avec une saveur harmonieuse.\n\nCela semble facile, mais équilibrer une glace est un art !\n\nEntrez les grammes des ingrédients et appuyez sur 'Calculer' pour obtenir la recette parfaite.",
        "errore_input": "Erreur : Veuillez entrer uniquement des nombres dans les champs.",
        "errore_peso_zero": "Erreur : Le poids total des ingrédients ne peut pas être zéro.",
        "ingredienti": {
            "Latte": "Lait",
            "Panna": "Crème",
            "Latte Scremato Polvere": "Lait Écrémé en Poudre",
            "Saccarosio": "Saccharose",
            "Destrosio": "Dextrose",
            "Glucosio": "Glucose",
            "Frutta Secca": "Fruits Secs",
            "Frutta Fresca": "Fruits Frais",
            "Inulina": "Inuline",
        },
    },
    "🇪🇸 Español": {
        "titolo": "El Helado Artesanal",
        "lingua_nome": "Español",
        "ingredienti_label": "Introduce los gramos de los ingredientes:",
        "calcola": "Calcular Equilibrio",
        "risultati": "Resultados del Equilibrio:",
        "salva_ricetta": "Guardar Receta",
        "carica_ricetta": "Cargar Receta",
        "condividi": "Compartir",
        "esci": "Salir",
        "zuccheri_totali": "Azúcares Totales",
        "grassi_totali": "Grasas Totales",
        "slm": "Sólidos No Grasos (SLM)",
        "solidi_totali": "Sólidos Totales",
        "pod": "POD - Poder Edulcorante",
        "pac": "PAC - Poder Anticongelante",
        "altri_solidi": "Otros Sólidos",
        "slng": "Sólidos Lácteos No Grasos (SLNG)",
        "neutro_5": "Neutro 5 (Tara, Guar)",
        "avviso_latte_scremato": "La leche en polvo desnatada supera el 12% del peso total",
        "condividi_testo_iniziale": "Aquí está mi receta de helado:\n\n",
        "condividi_risultati": "\nResultados del equilibrio:\n",
        "placeholder": "Introduce los gramos",
        "guida": "Guía",
        "guida_titolo": "Guía de uso",
        "guida_testo": "¿Alguna vez has encontrado grumos en un helado o probado uno que se derrite demasiado rápido? Estos defectos suelen surgir de un equilibrio incorrecto de los ingredientes. Si la mezcla no está equilibrada, el helado puede resultar demasiado líquido, duro o arenoso debido a la formación de cristales de hielo o lactosa. El sabor también puede verse afectado, volviéndose demasiado dulce.\n\nUn buen equilibrio, por otro lado, garantiza un helado cremoso, con la consistencia adecuada, sin grumos y con un sabor armonioso.\n\n¡Parece fácil, pero equilibrar un helado es un arte!\n\nIntroduce los gramos de los ingredientes y presiona 'Calcular' para obtener la receta perfecta.",
        "errore_input": "Error: Introduce solo números en los campos.",
        "errore_peso_zero": "Error: El peso total de los ingredientes no puede ser cero.",
        "ingredienti": {
            "Latte": "Leche",
            "Panna": "Crema",
            "Latte Scremato Polvere": "Leche en Polvo Desnatada",
            "Saccarosio": "Sacarosa",
            "Destrosio": "Dextrosa",
            "Glucosio": "Glucosa",
            "Frutta Secca": "Frutos Secos",
            "Frutta Fresca": "Frutas Frescas",
            "Inulina": "Inulina",
        },
    },
    "🇩🇪 Deutsch": {
        "titolo": "Das Artisan-Eis",
        "lingua_nome": "Deutsch",
        "ingredienti_label": "Geben Sie die Gramm der Zutaten ein:",
        "calcola": "Berechnung des Gleichgewichts",
        "risultati": "Ergebnisse des Gleichgewichts:",
        "salva_ricetta": "Rezept speichern",
        "carica_ricetta": "Rezept laden",
        "condividi": "Teilen",
        "esci": "Beenden",
        "zuccheri_totali": "Gesamtzucker",
        "grassi_totali": "Gesamtfette",
        "slm": "Nicht-Fett Feststoffe (SLM)",
        "solidi_totali": "Gesamtfeststoffe",
        "pod": "POD - Süßkraft",
        "pac": "PAC - Frostschutzkraft",
        "altri_solidi": "Andere Feststoffe",
        "slng": "Nicht-Fett Milchfeststoffe (SLNG)",
        "neutro_5": "Neutro 5 (Tara, Guar)",
        "avviso_latte_scremato": "Magermilchpulver übersteigt 12% des Gesamtgewichts",
        "condividi_testo_iniziale": "Hier ist mein Eisrezept:\n\n",
        "condividi_risultati": "\nErgebnisse der Bilanzierung:\n",
        "placeholder": "Geben Sie die Gramm ein",
        "guida": "Anleitung",
        "guida_titolo": "Benutzerhandbuch",
        "guida_testo": "Haben Sie schon einmal Klumpen in einem Eis gefunden oder eines probiert, das zu schnell schmilzt? Diese Mängel entstehen oft durch eine falsche Balance der Zutaten. Wenn die Mischung nicht ausgewogen ist, kann das Eis zu flüssig, hart oder sandig werden, weil sich Eiskristalle oder Laktose bilden. Auch der Geschmack kann darunter leiden und zu süß werden.\n\nEine gute Balance hingegen garantiert ein cremiges Eis mit der richtigen Konsistenz, ohne Klumpen und mit einem harmonischen Geschmack.\n\nEs scheint einfach, aber die Balance eines Eises ist eine Kunst!\n\nGeben Sie die Gramm der Zutaten ein und drücken Sie 'Berechnen', um das perfekte Rezept zu erhalten.",
        "errore_input": "Fehler: Bitte geben Sie nur Zahlen in die Felder ein.",
        "errore_peso_zero": "Fehler: Das Gesamtgewicht der Zutaten darf nicht null sein.",
        "ingredienti": {
            "Latte": "Milch",
            "Panna": "Sahne",
            "Latte Scremato Polvere": "Magermilchpulver",
            "Saccarosio": "Saccharose",
            "Destrosio": "Dextrose",
            "Glucosio": "Glucose",
            "Frutta Secca": "Trockenfrüchte",
            "Frutta Fresca": "Frisches Obst",
            "Inulina": "Inulin",
        },
    },
    "🇷🇺 Русский": {
        "titolo": "Артизанское Мороженое",
        "lingua_nome": "Русский",
        "ingredienti_label": "Введите граммы ингредиентов:",
        "calcola": "Рассчитать Баланс",
        "risultati": "Результаты Баланса:",
        "salva_ricetta": "Сохранить Рецепт",
        "carica_ricetta": "Загрузить Рецепт",
        "condividi": "Поделиться",
        "esci": "Выход",
        "zuccheri_totali": "Общее количество сахара",
        "grassi_totali": "Общее количество жиров",
        "slm": "Нежирные Твердые Вещества (SLM)",
        "solidi_totali": "Общее количество твердых веществ",
        "pod": "POD - Сладость",
        "pac": "PAC - Антифризная Мощность",
        "altri_solidi": "Другие Твердые Вещества",
        "slng": "Нежирные Молочные Твердые Вещества (SLNG)",
        "neutro_5": "Нейтро 5 (Тара, Гуар)",
        "avviso_latte_scremato": "Обезжиренное молоко превышает 12% от общего веса",
        "condividi_testo_iniziale": "Вот мой рецепт мороженого:\n\n",
        "condividi_risultati": "\nРезультаты балансировки:\n",
        "placeholder": "Введите граммы",
        "guida": "Руководство",
        "guida_titolo": "Руководство пользователя",
        "guida_testo": "Вам когда-нибудь попадались комочки в мороженом или вы пробовали мороженое, которое слишком быстро тает? Эти дефекты часто возникают из-за неправильного баланса ингредиентов. Если смесь не сбалансирована, мороженое может получиться слишком жидким, твердым или песчаным из-за образования кристаллов льда или лактозы. Вкус также может пострадать, став слишком сладким.\n\nХороший баланс, напротив, гарантирует кремовое мороженое с правильной консистенцией, без комочков и с гармоничным вкусом.\n\nКажется, что это просто, но сбалансировать мороженое — это искусство!\n\nВведите граммы ингредиентов и нажмите 'Рассчитать', чтобы получить идеальный рецепт.",
        "errore_input": "Ошибка: Вводите только числа в поля.",
        "errore_peso_zero": "Ошибка: Общий вес ингредиентов не может быть нулевым.",
        "ingredienti": {
            "Latte": "Молоко",
            "Panna": "Сливки",
            "Latte Scremato Polvere": "Обезжиренное Молочное Порошок",
            "Saccarosio": "Сахароза",
            "Destrosio": "Декстроза",
            "Glucosio": "Глюкоза",
            "Frutta Secca": "Сухофрукты",
            "Frutta Fresca": "Свежие Фрукты",
            "Inulina": "Инулин",
        },
    },
}