descrizioni_ingredienti = {
    "🇮🇹 Italiano": {
        "Latte": "Il latte è un ingrediente base per il gelato, fornisce liquidi e solidi del latte.",
        "Panna": "La panna aumenta il contenuto di grassi nel gelato, rendendolo più cremoso.",
        "Latte Scremato Polvere": "Il latte scremato in polvere aggiunge solidi del latte senza grassi.",
        "Saccarosio": "Il saccarosio è lo zucchero comune, fornisce dolcezza e struttura e abbassa il punto di congelamento.",
        "Destrosio": "Il destrosio ha un potere dolcificante inferiore al saccarosio e aiuta a controllare la cristallizzazione.",
        "Glucosio": "Il glucosio è uno zucchero semplice che migliora la consistenza del gelato.",
        "Frutta Secca": "La frutta secca aggiunge grassi e aromi naturali al gelato.",
        "Frutta Fresca": "La frutta fresca aggiunge zuccheri naturali e aromi al gelato.",
        "Inulina": "L'inulina è una fibra prebiotica che può migliorare la texture del gelato.",
    },
    "🇬🇧 English": {
        "Latte": "Milk is a base ingredient for gelato, providing liquids and milk solids.",
        "Panna": "Cream increases the fat content in gelato, making it creamier.",
        "Latte Scremato Polvere": "Skimmed milk powder adds milk solids without fat.",
        "Saccarosio": "Sucrose is common sugar, providing sweetness, structure, and lowering the freezing point.",
        "Destrosio": "Dextrose has a lower sweetening power than sucrose and helps control crystallization.",
        "Glucosio": "Glucose is a simple sugar that improves the consistency of gelato.",
        "Frutta Secca": "Dried fruit adds fats and natural flavors to gelato.",
        "Frutta Fresca": "Fresh fruit adds natural sugars and flavors to gelato.",
        "Inulina": "Inulin is a prebiotic fiber that can improve the texture of gelato.",
    },
    "🇫🇷 Français": {
        "Latte": "Le lait est un ingrédient de base pour le gelato, fournissant des liquides et des solides du lait.",
        "Panna": "La crème augmente la teneur en matières grasses du gelato, le rendant plus crémeux.",
        "Latte Scremato Polvere": "La poudre de lait écrémé ajoute des solides du lait sans matières grasses.",
        "Saccarosio": "Le saccharose est le sucre commun, fournissant de la douceur, de la structure et abaissant le point de congélation.",
        "Destrosio": "Le dextrose a un pouvoir sucrant inférieur au saccharose et aide à contrôler la cristallisation.",
        "Glucosio": "Le glucose est un sucre simple qui améliore la consistance du gelato.",
        "Frutta Secca": "Les fruits secs ajoutent des graisses et des arômes naturels au gelato.",
        "Frutta Fresca": "Les fruits frais ajoutent des sucres naturels et des arômes au gelato.",
        "Inulina": "L'inuline est une fibre prébiotique qui peut améliorer la texture du gelato.",
    },
    "🇪🇸 Español": {
        "Latte": "La leche es un ingrediente básico para el gelato, proporciona líquidos y sólidos lácteos.",
        "Panna": "La crema aumenta el contenido de grasa en el gelato, haciéndolo más cremoso.",
        "Latte Scremato Polvere": "La leche en polvo desnatada añade sólidos lácteos sin grasa.",
        "Saccarosio": "La sacarosa es el azúcar común, proporciona dulzura, estructura y reduce el punto de congelación.",
        "Destrosio": "La dextrosa tiene un poder edulcorante inferior a la sacarosa y ayuda a controlar la cristalización.",
        "Glucosio": "La glucosa es un azúcar simple que mejora la consistencia del gelato.",
        "Frutta Secca": "Los frutos secos añaden grasas y sabores naturales al gelato.",
        "Frutta Fresca": "Las frutas frescas añaden azúcares naturales y sabores al gelato.",
        "Inulina": "La inulina es una fibra prebiótica que puede mejorar la textura del gelato.",
    },
    "🇩🇪 Deutsch": {
        "Latte": "Milch ist eine Grundzutat für Gelato, liefert Flüssigkeiten und Milchfeststoffe.",
        "Panna": "Sahne erhöht den Fettgehalt im Gelato und macht es cremiger.",
        "Latte Scremato Polvere": "Magermilchpulver fügt Milchfeststoffe ohne Fett hinzu.",
        "Saccarosio": "Saccharose ist der gewöhnliche Zucker, liefert Süße, Struktur und senkt den Gefrierpunkt.",
        "Destrosio": "Dextrose hat eine geringere Süßkraft als Saccharose und hilft, die Kristallisation zu kontrollieren.",
        "Glucosio": "Glukose ist ein einfacher Zucker, der die Konsistenz von Gelato verbessert.",
        "Frutta Secca": "Trockenfrüchte fügen Fette und natürliche Aromen zum Gelato hinzu.",
        "Frutta Fresca": "Frisches Obst fügt natürliche Zucker und Aromen zum Gelato hinzu.",
        "Inulina": "Inulin ist eine präbiotische Faser, die die Textur von Gelato verbessern kann.",
    },
    "🇷🇺 Русский": {
        "Latte": "Молоко является основным ингредиентом для мороженого, обеспечивает жидкость и молочные твердые вещества.",
        "Panna": "Сливки увеличивают содержание жира в мороженом, делая его более кремовым.",
        "Latte Scremato Polvere": "Обезжиренное сухое молоко добавляет молочные твердые вещества без жира.",
        "Saccarosio": "Сахароза — это обычный сахар, обеспечивает сладость, структуру и снижает точку замерзания.",
        "Destrosio": "Декстроза имеет меньшую сладость, чем сахароза, и помогает контролировать кристаллизацию.",
        "Glucosio": "Глюкоза — это простой сахар, который улучшает консистенцию мороженого.",
        "Frutta Secca": "Сухофрукты добавляют жиры и натуральные ароматы в мороженое.",
        "Frutta Fresca": "Свежие фрукты добавляют натуральные сахара и ароматы в мороженое.",
        "Inulina": "Инулин — это пребиотическая клетчатка, которая может улучшить текстуру мороженого.",
    },
}